name: Deploy

on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/deployctl@v1
        with:
          project: illyyllm-api
          entrypoint: ./mod.ts
          import-map: ./import_map.json
